Update deop

diff --git a/system/bin/deop b/system/bin/deop
--- a/system/bin/deop
+++ b/system/bin/deop
@@ -111,27 +111,40 @@ get_package_size() {
 }
 
 script_mode() {
-  is_russian && echo -n "Выбери режим скрипта (1: Автоматический, 2: Ручной): " || echo -n "Select the script mode (1: Automatic, 2: Manual): "
-  read -r WORK
+  while true; do
+    is_russian && echo -n "Выбери режим скрипта (1: Автоматический, 2: Ручной): " || echo -n "Select the script mode (1: Automatic, 2: Manual): "
+    read -r WORK
 
-  if [[ "$WORK" -ne 1 && "$WORK" -ne 2 ]]; then
+    if [[ "$WORK" -eq 1 || "$WORK" -eq 2 ]]; then
+      break
+    fi
+
     is_russian && echo "Ошибка: Недопустимое значение для режима скрипта" || echo "Error: Invalid value for the script mode"
-    exit 1
-  fi
+  done
 
   if [ "$WORK" -eq 2 ]; then
-    is_russian && echo -n "Выбери приложения (1: Пользовательские, 2: Системные, 3: Все): " || echo -n "Select apps (1: User, 2: System, 3: All): "
-    read -r PACKAGES
-  
-    msg_select
-    is_russian && echo -n "Выбери профиль (1: everything-profile, 2: speed-profile): " || echo -n "Select profile (1: everything-profile, 2: speed-profile): "
-    read -r SETTINGS
+    while true; do
+      is_russian && echo -n "Выбери приложения (1: Пользовательские, 2: Системные, 3: Все): " || echo -n "Select apps (1: User, 2: System, 3: All): "
+      read -r PACKAGES
 
-    case "$SETTINGS" in
-      1) profile="everything-profile" ;;
-      2) profile="speed-profile" ;;
-      *) log_msg "$(is_russian && echo "Ошибка: Неверный выбор профиля" || echo "Error: Invalid profile selection")"; exit 1 ;;
-    esac
+      if [[ "$PACKAGES" -eq 1 || "$PACKAGES" -eq 2 || "$PACKAGES" -eq 3 ]]; then
+        break
+      fi
+
+      is_russian && echo "Ошибка: Недопустимое значение для приложений" || echo "Error: Invalid value to apps"
+    done
+
+    msg_select
+    while true; do
+      is_russian && echo -n "Выбери профиль (1: everything-profile, 2: speed-profile): " || echo -n "Select profile (1: everything-profile, 2: speed-profile): "
+      read -r SETTINGS
+
+      case "$SETTINGS" in
+        1) profile="everything-profile"; break ;;
+        2) profile="speed-profile"; break ;;
+        *) log_msg "$(is_russian && echo "Ошибка: Неверный выбор профиля" || echo "Error: Invalid profile selection")" ;;
+      esac
+    done
   else
     PACKAGES=3
     profile="auto"
@@ -141,23 +154,26 @@ script_mode() {
     1) packages_file=$(pm list packages -3 | awk '{sub("^package:", ""); print}') ;;  # user
     2) packages_file=$(pm list packages -s | awk '{sub("^package:", ""); print}') ;;  # system
     3) packages_file=$(pm list packages | awk '{sub("^package:", ""); print}') ;;     # all
-    *) log_msg "$(is_russian && echo "Ошибка: Недопустимое значение для приложений" || echo "Error: Invalid value to apps")"; exit 1 ;;
   esac
 
-  is_russian && echo -n "Выбери максимальное число процессов (10 - максимум): " || echo -n "Select the maximum count of PROCESSES (10 - max): "
-  read -r PARTS
-  if [ "$PARTS" -lt 1 ] || [ "$PARTS" -gt 10 ]; then
+  while true; do
+    is_russian && echo -n "Выбери максимальное число процессов (10 - максимум): " || echo -n "Select the maximum count of PROCESSES (10 - max): "
+    read -r PARTS
+
+    if [[ "$PARTS" -ge 1 && "$PARTS" -le 10 ]]; then
+      break
+    fi
+
     log_msg "$(is_russian && echo "Ошибка: ПРОЦЕССОВ должно быть от 1 до 10" || echo "Error: PROCESSES must be between 1 and 10")" >&2
-    exit 1
-  fi
+  done
 
   log_msg "$(is_russian && echo "¦ Изменение режима производительности на максимальный" || echo "¦ Changing the performance mode to the maximum")"
   setprop sys.perf.profile perfomance
   is_russian && echo "¦ Сортировка приложений по размеру" || echo "¦ Sorting applications by size"
 
   sorted_packages=$(while read -r pkg; do
-  size=$(get_package_size "$pkg")
-  echo "$size $pkg"
+    size=$(get_package_size "$pkg")
+    echo "$size $pkg"
   done <<< "$packages_file" | sort -nr)
 
   total_count=$(echo "$sorted_packages" | wc -l)
@@ -221,12 +237,11 @@ script_mode() {
 
 select_app_by_name() {
   packages_file=$(pm list packages | awk '{sub("^package:", ""); print}')
-  
   is_russian && echo -n "Введите имя или часть имени приложения: " || echo -n "Enter the name or part of the app name: "
   read -r app_name
-  
-  matched_apps=$(echo "$packages_file" | grep -i "$app_name")
 
+  matched_apps=$(echo "$packages_file" | grep -i "$app_name")
+   
   if [ -n "$matched_apps" ]; then
     is_russian && echo "Найдены следующие приложения:" || echo "Found the following applications:"
     apps_count=0
@@ -239,46 +254,50 @@ select_app_by_name() {
     if [ "$apps_count" -eq 1 ]; then
       selected_apps="$matched_apps"
     else
-      is_russian && echo -n "Выбери приложение (1: все, 2: конкретное): " || echo -n "Select an app (1: all, 2: specific): "
-      read -r choice
+      while true; do
+        is_russian && echo -n "Выбери приложение (1: все, 2: конкретное): " || echo -n "Select an app (1: all, 2: specific): "
+        read -r choice
 
-      if [ "$choice" -eq 1 ]; then
-        selected_apps="$matched_apps"
-      elif [ "$choice" -eq 2 ]; then
-        is_russian && echo -n "Введите номер приложения для компиляции: " || echo -n "Enter the app number to compile: "
-        read -r app_number
-      
-        selected_app=$(echo "$matched_apps" | sed -n "${app_number}p")
-        if [ -n "$selected_app" ]; then
-          selected_apps="$selected_app"
+        if [ "$choice" -eq 1 ]; then
+          selected_apps="$matched_apps"
+          break
+        elif [ "$choice" -eq 2 ]; then
+          is_russian && echo -n "Введите номер приложения для компиляции: " || echo -n "Enter the app number to compile: "
+          read -r app_number
+
+          selected_app=$(echo "$matched_apps" | sed -n "${app_number}p")
+          if [ -n "$selected_app" ]; then
+            selected_apps="$selected_app"
+            break
+          else
+            is_russian && echo "Ошибка: Некорректный номер приложения" || echo "Error: Invalid app number"
+          fi
         else
-          is_russian && echo "Ошибка: Некорректный номер приложения" || echo "Error: Invalid app number"
-          exit 1
+          is_russian && echo "Неверный выбор. Пожалуйста, выберите 1 или 2" || echo "Invalid selection. Please choose 1 or 2"
         fi
-      else
-        is_russian && echo "Неверный выбор. Пожалуйста, выберите 1 или 2" || echo "Invalid selection. Please choose 1 or 2"
-        exit 1
-      fi
+      done
     fi
-   
-    msg_select
+  else
+    is_russian && echo "Приложение с именем $app_name не найдено. Попробуйте снова." || echo "Application with the name $app_name not found. Please try again."
+    return 1
+  fi
+
+  msg_select
+  while true; do
     is_russian && echo -n "Выбери профиль (1: everything-profile, 2: speed-profile): " || echo -n "Select profile (1: everything-profile, 2: speed-profile): "
     read -r SETTINGS
 
     case "$SETTINGS" in
-      1) profile="everything-profile" ;;
-      2) profile="speed-profile" ;;
-      *) log_msg "$(is_russian && echo "Ошибка: Неверный выбор профиля" || echo "Error: Invalid profile selection")"; exit 1 ;;
+      1) profile="everything-profile"; break ;;
+      2) profile="speed-profile"; break ;;
+      *) log_msg "$(is_russian && echo "Ошибка: Неверный выбор профиля" || echo "Error: Invalid profile selection")";;
     esac
+  done
 
-    echo ""
-    for app in $selected_apps; do
-      compile_profile 0 "$app" "$profile"
-    done
-  else
-    is_russian && echo "Приложение с именем $app_name не найдено." || echo "Application with the name $app_name not found."
-    exit 1
-  fi
+  echo ""
+  for app in $selected_apps; do
+    compile_profile 0 "$app" "$profile"
+  done
 }
 
 module_update() {
@@ -324,17 +343,23 @@ module_update() {
 }
 
 handle_selection() {
-  case "$1" in
-    1) script_mode ;;
-    2) select_app_by_name ;;
-    3)
-      cmd package compile --reset -a
-      is_russian && echo "Профиль приложений очищен" || echo "Apps profile cleared"
-      exit 1
-      ;;
-    4) module_update ;;
-    *) is_russian && echo "Ошибка: Неверный выбор. Пожалуйста, выберите от 1 до 4" || echo "Error: Invalid selection. Please select from 1 to 4"; exit 1 ;;
-  esac
+  while true; do
+    case "$1" in
+      1) script_mode; break ;;
+      2) select_app_by_name; break ;;
+      3)
+        cmd package compile --reset -a
+        is_russian && echo "Профиль приложений очищен" || echo "Apps profile cleared"
+        continue ;;
+      4) module_update; break ;;
+      *)
+        is_russian && echo "Ошибка: Неверный выбор. Пожалуйста, выберите от 1 до 4" || echo "Error: Invalid selection. Please select from 1 to 4"
+        ;;
+    esac
+    echo -n "$(is_russian && echo "Выберите опцию: " || echo "Select an option: ")" 
+    read -r selection
+    handle_selection "$selection"
+  done
 }
 
 show_menu() {
